/**
 * @file Automatically generated by barrelsby.
 */

export * from './app-routing.module';
export * from './app.component';
export * from './app.module';
export * from './admin/index';
export * from './shared/index';
